export * from './alojamiento.repository';
export * from './arbitro.repository';
export * from './director-tecnico.repository';
export * from './equipo.repository';
export * from './estadio.repository';
export * from './inicio-session.repository';
export * from './jugador.repository';
export * from './torneo.repository';
export * from './transporte.repository';
